- name: Create needed directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - /etc/transmission
    - /etc/prowlarr
    - /etc/vpn
    - /etc/jellyfin
    - /etc/jellyfin/cache

    - /mnt/mount/transmissionDownloads
    - /mnt/mount/jellyfinMedia

- name: Copy docker compose file
  template:
    src: compose.yaml.j2
    dest: /mnt/mount/docker/docker-compose.yaml
    owner: root
    group: root
    mode: "0644"

- name: Write env secrets from vault
  copy:
    content: |
      PIA_USERNAME={{ vault_pia_username }}
      PIA_PASSWORD={{ vault_pia_password }}
    dest: /mnt/mount/docker/.env
    owner: root
    group: root
    mode: "0600"
