---

- name: Set up Nebula
  hosts: all
  become: yes
  
  tasks:
    - name: Install Nebula apt package
      apt:
        name: nebula
        state: present
        update_cache: yes

    - name: If host is marked as a lighthouse, ensure lighthouse config is present
      copy:
        src: files/lighthouse_config.yaml
        dest: /etc/nebula/config.yaml
        owner: root
        group: root
        mode: '0644'
      when: "'lighthouse' in group_names"