# - name: Add Drv1 PARTUUID to fstab
#   lineinfile:
#     dest: /etc/fstab
#     line: "PARTUUID=9f9dfead-c8bd-40bc-a012-7c3fa996e610 /mnt/drv1 ext4 defaults"
#     state: present
---
- name: Configure Drives Auto-Mounting
  hosts: all

# - name: Ensure mount point exists
#   file:



  vars_files:
    - drive_configs.yml







  tasks:
  