---

- name: Ensure fstab is updated with drive configurations
  lineinfile:
    regexp: '^PARTUUID={{ item.partuuid }}'
    path: /etc/fstab
    line: 'PARTUUID={{ item.partuuid }} {{ mount_point }}/{{ item.name }} {{ item.fs_type }} defaults,auto 0 2'
    state: present
  loop: "{{ drive_configs }}"

- name: Ensure mount points exist and have appropriate permissions
  file:
    path: "{{ mount_point }}/{{ item.name }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop: "{{ drive_configs }}"

- name: Systemctl daemon-reload
  command: systemctl daemon-reload

- name: Mount all filesystems
  command: mount -a