# add block to /etc/udev/rules.d/70-pcpanel.rules
# SUBSYSTEM=="usb", ATTRS{idVendor}=="04D8", ATTRS{idProduct}=="eb52", TAG+="uaccess"
# SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="a3c4", TAG+="uaccess"
# SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="a3c5", TAG+="uaccess"

- name: Check if we've already set up pcpanel
  stat:
    path: /etc/udev/rules.d/70-pcpanel.rules
  register: pcpanel_rules_file

- name: Check if we've installed the deb file before
  stat:
    path: /var/pcpanel_installed
  register: pcpanel_deb_file

- name: Ensure pulseaudio is installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - pulseaudio
    - pulseaudio-utils
  when: not pcpanel_rules_file.stat.exists

- name: Create required directories for pcpanel
  file:
    path: /etc/udev/rules.d
    state: directory
    mode: "0755"
  when: not pcpanel_rules_file.stat.exists

- name: Add udev rules for pcpanel
  copy:
    content: |
      # SUBSYSTEM=="usb", ATTRS{idVendor}=="04D8", ATTRS{idProduct}=="eb52", TAG+="uaccess"
      SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="a3c4", TAG+="uaccess"
      SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="a3c5", TAG+="uaccess"
    dest: /etc/udev/rules.d/70-pcpanel.rules
    mode: "0644"
    owner: root
    group: root
  when: not pcpanel_rules_file.stat.exists

- name: Reload udev rules
  shell: udevadm control --reload-rules && udevadm trigger
  when: not pcpanel_rules_file.stat.exists

- name: Download pcpanel deb file
  get_url:
    url: "https://github.com/nvdweem/PCPanel/releases/download/v1.7.1/pcpanel_1.7.1_amd64.deb"
    dest: /tmp/pcpanel_1.7.1_amd64.deb
    mode: "0644"
  when: not pcpanel_deb_file.stat.exists

- name: Install pcpanel deb file
  apt:
    deb: /tmp/pcpanel_1.7.1_amd64.deb
  when: not pcpanel_deb_file.stat.exists

- name: Create file to indicate pcpanel installed
  file:
    path: /var/pcpanel_installed
    state: touch
    mode: "0644"
  when: not pcpanel_deb_file.stat.exists
