services:

### START DOWNLOAD
  vpn:
    container_name: vpn
    profiles:
      - download
    image: qmcgaw/gluetun:v3.40
    cap_add:
      - NET_ADMIN # Quin does not like these
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${PATH_ETC}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=Netherlands
      - OPENVPN_USER=${PIA_USERNAME}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - UPDATER_PERIOD=24h
      - PORT_FORWARD_ONLY=true
      - VPN_PORT_FORWARDING=on
    ports:
      - 9091:9091         # Transmission
      - 51413:51413       # Transmission
      - 51413:51413/udp   # Transmission
      - 9696:9696         # Prowlarr
      - 7878:7878         # Radarr
      - 8989:8989         # Sonarr
      - 8686:8686         # Lidarr
      - 6767:6767         # Bazarr
      - 3333:3333         # bitmagnet API and WebUI port
      - 3334:3334/tcp     # bitmagnet BitTorrent ports
      - 3334:3334/udp     # bitmagnet BitTorrent ports
      # - 5055:5055       # seerr
      - 7474:7474         # Autobrr
    restart: unless-stopped

  transmission:
    container_name: transmission
    profiles:
      - download
      # - donotstart
    image: lscr.io/linuxserver/transmission:latest
    user: 700:700
    network_mode: "service:vpn"
    environment:
      - TZ=${TZ}
      - PUID=700
      - PGID=700
    volumes:
      - ${PATH_ETC}/transmission:/config
      - /storage/transmission/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    profiles:
      - download
    image: lscr.io/linuxserver/prowlarr:latest
    user: 700:700
    network_mode: "service:vpn"
    environment:
      - TZ=${TZ}
      - PUID=700
      - PGID=700
    volumes:
      - ${PATH_ETC}/prowlarr:/config
    depends_on:
      vpn:
        condition: service_started
        restart: true
        required: true
    restart: unless-stopped

  radarr:
    container_name: radarr
    profiles:
      - download
    image: lscr.io/linuxserver/radarr:latest
    user: 700:700
    network_mode: "service:vpn"
    environment:
      - PUID=700
      - PGID=700
      - TZ=${TZ}
    volumes:
      - ${PATH_ETC}/radarr:/config
      - /storage/media:/media                       # Access to media library
      - /storage/transmission/downloads:/downloads  # Access to transmission downloads
    depends_on:
      vpn:
        condition: service_started
        restart: true
        required: true
      prowlarr:
        condition: service_started
        restart: true
        required: true
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    profiles:
      - download
    image: lscr.io/linuxserver/sonarr:latest
    user: 700:700
    network_mode: "service:vpn"
    environment:
      - PUID=700
      - PGID=700
      - TZ=${TZ}
    volumes:
      - ${PATH_ETC}/sonarr:/config
      - /storage/media:/media                       # Access to media library
      - /storage/transmission/downloads:/downloads  # Access to transmission downloads
    depends_on:
      vpn:
        condition: service_started
        restart: true
        required: true
      prowlarr:
        condition: service_started
        restart: true
        required: true
    restart: unless-stopped
  
  lidarr:
    profiles:
      - download
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    user: 700:700
    network_mode: "service:vpn"
    environment:
      - PUID=700
      - PGID=700
      - TZ=${TZ}
    volumes:
      - ${PATH_ETC}/lidarr:/config
      - /storage/media:/media                       # Access to media library
      - /storage/transmission/downloads:/downloads  # Access to transmission downloads
    depends_on:
      vpn:
        condition: service_started
        restart: true
        required: true
      prowlarr:
        condition: service_started
        restart: true
        required: true
    restart: unless-stopped

  bazarr:
    profiles:
      - download
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    user: 700:700
    network_mode: "service:vpn"
    environment:
      - PUID=700
      - PGID=700
      - TZ=${TZ}
    volumes:
      - ${PATH_ETC}/bazarr:/config
      - /storage/media:/media                       # Access to media library
    depends_on:
      vpn:
        condition: service_started
        restart: true
        required: true
      prowlarr:
        condition: service_started
        restart: true
        required: true
    restart: unless-stopped

  bitmagnet:
    container_name: bitmagnet
    profiles:
      - download
    image: ghcr.io/bitmagnet-io/bitmagnet:latest
    user: 700:700
    restart: unless-stopped
    network_mode: "service:vpn"
    environment:
      - POSTGRES_PASSWORD=${BITMAGENT_DB_PASS}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - PUID=700
      - PGID=700
    volumes:
      - ${PATH_ETC}/bitmagnet:/root/.config/bitmagnet
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      # disable the next line to run without DHT crawler
      - --keys=dht_crawler
    depends_on:
      bitmagnetpostgres:
        condition: service_healthy

  bitmagnetpostgres:
    container_name: bitmagnet-postgres
    profiles:
      - download
    image: postgres:16-alpine
    network_mode: "service:vpn"
    volumes:
      - ${PATH_ETC}/bitmagnet-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${BITMAGENT_DB_PASS}
      - POSTGRES_DB=bitmagnet
      - PGUSER=postgres
    shm_size: 1g
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s

  seerr:
    container_name: seerr
    profiles:
      - download
    image: ghcr.io/seerr-team/seerr:latest
    user: 700:700
    init: true
    ports:
      - 5055:5055
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=debug
      - PUID=700
      - PGID=700
    volumes:
      - ${PATH_ETC}/seer:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  aurral:
    container_name: aurral
    profiles:
      - download
    image: ghcr.io/lklynet/aurral:latest
    user: 700:700
    ports:
      - 3001:3001
    environment:
      - DOWNLOAD_FOLDER=${DL_FOLDER:-./data/downloads}
      - PUID=700
      - PGID=700
    volumes:
      - ${PATH_ETC}/aurral:/app/backend/data
      - /storage/aurral:/app/downloads
    restart: unless-stopped

  ### END DOWNLOAD

  ### INFRA
  prometheus:
    profiles:
      - infra
    container_name: prometheus
    image: prom/prometheus
    user: 700:700
    ports:
      - 9090:9090
    volumes:
      - ${PATH_ETC}/prometheus:/prometheus
      - ./bin/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - PUID=700
      - PGID=700
    restart: unless-stopped

  meshchatx:
    profiles:
      - infra
    container_name: meshchatx
    image: quad4io/meshchatx:latest
    privileged: true
    group_add:
      - 27 # Dialout group hehe
    user: 1000:700
    ports:
      - 8000:8000
      - 4242:4242
    volumes:
      - ${PATH_ETC}/meshchatx:/config
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - PUID=700
      - PGID=700
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  ### END INFRA

  ### START APP
  soupclownsite:
    profiles:
      - app
    container_name: soupclownsite
    image: nginx:alpine
    ports:
      - 8075:80
    volumes:
      - ./bin/soupclown:/usr/share/nginx/html
    command: [ "nginx", "-g", "daemon off;" ]
    restart: unless-stopped

  navidrome:
    profiles:
      - app
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 700:700
    ports:
      - "4533:4533"
    volumes:
      - ${PATH_ETC}/navidrome:/data
      - /storage/media/Music:/music
    environment:
      - PUID=700
      - PGID=700
    restart: unless-stopped

  metube:
    profiles:
      - app
    image: ghcr.io/alexta69/metube
    user: 700:700
    container_name: metube
    ports:
      - "8081:8081"
    volumes:
      - ./bin/metube-options.json:/config/metube-options.json # Use config from repo :)
      - /storage/metube/downloads:/downloads
    environment:
      - YTDL_OPTIONS_FILE=/config/metube-options.json
      - PUID=700
      - PGID=700
    restart: unless-stopped

  soupclownmc:
    profiles:
      - app
    image: itzg/minecraft-server:latest
    container_name: soupclownmc
    user: 700:700
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - PUID=700
      - PGID=700
    volumes:
      - ${PATH_ETC}/soupclownmc:/data
    restart: unless-stopped

  nextcloudDb:
    profiles:
      - app
    container_name: nextcloud-db
    image: mariadb:lts
    user: 700:700
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ${PATH_ETC}/nextcloud/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASS}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USERNAME}
    restart: unless-stopped

  nextcloudRedis:
    profiles:
      - app
    container_name: nextcloud-redis
    image: redis:alpine
    user: 700:700
    environment:
      - PUID=700
      - PGID=700
    restart: unless-stopped

  nextcloud:
    profiles:
      - app
    container_name: nextcloud
    image: nextcloud
    user: 700:700
    ports:
      - 5836:80
    volumes:
      - ${PATH_ETC}/nextcloud/etc:/var/www/html
      - ./bin/nextcloud:/var/www/html/config
      - /storage/nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USERNAME}
      - MYSQL_HOST=nextcloudDb
      - PUID=700
      - PGID=700
    depends_on:
      - nextcloudRedis
      - nextcloudDb
    restart: unless-stopped

  harp_frpc_docker:
    profiles:
      - app
    cap_add:
      - NET_ADMIN # Quin does not like these
    container_name: harp_frpc_docker
    image: ghcr.io/nextcloud/nextcloud-appapi-harp:release
    volumes:
      - ./bin/frpc.toml:/etc/frpc.toml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HP_FRP_DISABLE_TLS=true
      - HP_SHARED_KEY=${NEXTCLOUD_HARP_FRPC_KEY}
      - NC_INSTANCE_URL=https://cloud.soupclown.com
    command: -c=/etc/frpc.toml
    restart: unless-stopped
  ### END APP

  #DONOTSTART
  gitea:
    profiles:
      - donotstart
    container_name: gitea
    image: docker.gitea.com/gitea:1.26.1
    user: 700:700
    ports:
      - 3031:3000
      - 8022:22
    volumes:
      - ${PATH_ETC}/gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_DB_USERNAME}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__database__HOST=giteadb:5432
    restart: unless-stopped
    depends_on:
      - giteadb

  #DONOTSTART
  giteadb:
    profiles:
      - donotstart
    container_name: gitea-postgres
    image: docker.io/library/postgres:14
    user: 1000:700
    environment:
      - POSTGRES_USER=${GITEA_DB_USERNAME}
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ${PATH_ETC}/gitea-postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 20s
      interval: 10s
    restart: unless-stopped
  
  #DONOTSTART
  lidatube:
    container_name: lidatube
    profiles:
      - donotstart
    image: thewicklowwolf/lidatube:latest
    user: 700:700
    volumes:
      - ${PATH_ETC}/lidatube:/lidatube/config
      - /storage/lidatube:/lidatube/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - attempt_lidarr_import=True
      - PUID=700
      - PGID=700
    ports:
      - 5000:5000
    restart: unless-stopped
