- name: Download cfssl binary
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssl_1.6.5_linux_amd64
    dest: /usr/local/bin/cfssl
    mode: '0755'

- name: Download cfssljson binary
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssljson_1.6.5_linux_amd64
    dest: /usr/local/bin/cfssljson
    mode: '0755'

- name: Download cfssl-certinfo binary
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssl-certinfo_1.6.5_linux_amd64
    dest: /usr/local/bin/cfssl-certinfo
    mode: '0755'
