- name: Install Copyparty via pip in virtualenv
  command: /opt/venv/bin/pip install copyparty

- name: Install cfssl 
  import_tasks: cfssl.yaml

- name: Create Copyparty config file
  ansible.builtin.template:
    src: copyparty.conf.j2
    dest: /etc/copyparty.conf
    owner: root
    group: root
    mode: '0644'

- name: Create systemd service for Copyparty
  ansible.builtin.template:
    src: copyparty.service.j2
    dest: /etc/systemd/system/copyparty.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Copyparty service
  ansible.builtin.systemd:
    name: copyparty
    enabled: yes
    state: started