---
- name: Install python and pip
  import_tasks: python.yaml

- name: Configure drives and mount points
  import_tasks: driveConfigTasks.yaml
# - name: Install and configure Docker
#   import_tasks: docker.yaml
