---
- name: Install python and pip
  import_tasks: python.yaml

- name: Configure drives and mount points
  import_tasks: driveConfigTasks.yaml

- name: Install Docker
  import_tasks: docker-install.yaml

- name: Install common packages
  apt:
    name:
      - btop
      - rclone
    state: present
    update_cache: yes
