# A role that updates the root soupclown env for all hosts
# All values will be set in the secrets and then copied to an env file on each host that hosts services
- name: Update env file for soupclown services
  copy:
    content: |
      #GLOBAL ENV VARS
      TZ="{{TZ}}"
      PATH_ETC="{{PATH_ETC}}"

      #API KEYS
      PIA_USERNAME="{{PIA_USERNAME}}"
      PIA_PASSWORD="{{PIA_PASSWORD}}"
      TMDB_API_KEY="{{TMDB_API_KEY}}"
      BITMAGENT_DB_PASS="{{BITMAGENT_DB_PASS}}"

      IMMICH_DB_PASSWORD="{{IMMICH_DB_PASSWORD}}"
      IMMICH_DB_USERNAME="{{IMMICH_DB_USERNAME}}"
      IMMICH_DB_DATABASE_NAME="{{IMMICH_DB_DATABASE_NAME}}"
      PAPERLESS_SECRET_KEY="{{PAPERLESS_SECRET_KEY}}"
      GITEA_DB_USERNAME="{{GITEA_DB_USERNAME}}"
      GITEA_DB_PASSWORD="{{GITEA_DB_PASSWORD}}"
    dest: /etc/.soupclown.env
    owner: root
    group: root
    mode: '0600'