---
- hosts: soupclown1
  become: yes
  roles:
    - sync_remote_code
  vars_files:
    - secrets.yaml

# - hosts: desktop
#   become: yes
#   roles:
#     - sync_remote_code
#     - update_env
#   vars_files:
#     - secrets.yaml