---
- hosts: pt1
  become: yes
  roles:
    - reticulum
  vars:
    radios:
      B407:
        name: B407
        serialpath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_54FC052298-if00
      5678:
        name: 5678
        serialpath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_54F7017826-if00
      D77E:
        name: D77E
        serialpath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_54F7017033-if00
      XXXX:
        enabled: "no"
        name: XXXX
        serialpath: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
      # C123:
      #   name: C123
      #   serialpath: /dev/ttyACM1
      #   frequency: 915000000
      #   bandwidth: 125000
      #   txpower: 14
