# get the installer script
# curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh

- name: Check if opentofu is installed
  stat:
    path: /var/opentofu_installed
  register: opentofu_installed_check

- name: Download installer script
  get_url:
    url: https://get.opentofu.org/install-opentofu.sh
    dest: /tmp/install-opentofu.sh
    mode: "0755"
  when: not opentofu_installed_check.stat.exists

- name: Make installer script executable
  command: chmod +x /tmp/install-opentofu.sh
  when: not opentofu_installed_check.stat.exists

- name: Install opentofu
  command: /tmp/install-opentofu.sh --install-method deb
  when: not opentofu_installed_check.stat.exists

- name: Remove installer script
  file:
    path: /tmp/install-opentofu.sh
    state: absent
  when: not opentofu_installed_check.stat.exists

- name: Create file indicating opentofu is installed
  file:
    path: /var/opentofu_installed
    state: touch
  when: not opentofu_installed_check.stat.exists
