- name: Check if lazydocker is installed
  stat:
    path: /var/lazydocker_installed
  register: lazydocker_installed_check

- name: Download install script for lazydocker
  get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /tmp/install_lazydocker.sh
    mode: "0755"
  when: not lazydocker_installed_check.stat.exists

- name: Run lazydocker installer script
  command: /tmp/install_lazydocker.sh
  when: not lazydocker_installed_check.stat.exists

- name: Create file indicating lazydocker is installed
  file:
    path: /var/lazydocker_installed
    state: touch
  when: not lazydocker_installed_check.stat.exists
