# NOTE: Never use apt for rclone, use official script

- name: Remove defualt packages
  apt:
    name:
      - firefox
      - thunderbird
    state: absent

- name: Install common packages
  apt:
    name:
      - btop
      - htop
      - desktop-file-utils
      - git
      - gh
      - ssh-import-id
      - python3-venv
      - python3-pip

- name: Install snap packages
  snap:
    name: "{{ item }}"
    state: present
  with_items:
    - vivaldi
    - signal-desktop

- name: Install python3 packages
  pip:
    name: "{{ item }}"
    state: present
    break_system_packages: yes
    executable: pip3
  with_items:
    - pyyaml
    - cryptography
    - passlib

- name: Install Docker
  import_tasks: docker-install.yaml
