- name: Check if rclone is installed
  stat:
    path: /var/rclone_installed
  register: rclone_installed_check

- name: Install rclone (mega)
  command:
    # This command is for sure not working but I ran it manually and it worked. So I blame ansible
    cmd: "curl https://rclone.org/install.sh | sudo bash ; touch /var/rclone_installed"
    creates: /var/rclone_installed
  when: not rclone_installed_check.stat.exists

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0770"
  with_items:
    - /root/.config/rclone
    - /mnt/mega

- name: Create rclone config
  copy:
    content: |
      [mega]
      type = mega
      user = tnuu9h362@mozmail.com
      pass = {{ rclone_mega_key }}

      [data]
      type = crypt
      remote = mega:enc
      password = {{ rclone_encPass_one }}
      password2 = {{ rclone_encPass_two }}
    dest: /root/.config/rclone/rclone.conf

- name: Write service file for rclone mount
  copy:
    content: |
      [Unit]
      Description=Rclone mount service
      After=local-fs.target network.target

      [Service]
      Type=simple
      User=root
      KillMode=control-group
      ExecStart=rclone mount data:enc /mnt/mega -vv \
        --vfs-cache-mode full \
        --allow-other \
        --umask 0 \
        --dir-perms 0777 \
        --file-perms 0777 \
        --dir-cache-time 300h
      ExecStop=umount /mnt/mega
      Restart=on-failure
      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/rclone.service
    mode: "0644"
    owner: root
    group: root

- name: Systemctl daemon-reload
  command: systemctl daemon-reload

- name: Enable and start rclone service
  systemd:
    name: rclone
    state: started
    enabled: yes
