
---
- name: Check if caddy config in sync
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: '0644'
  check_mode: yes
  register: caddy_config_check

- name: Report drift status
  ansible.builtin.debug:
    msg: >
      {{ 
        'UPDATE REQUIRED: Caddyfile on host (' + inventory_hostname + ') needs update'
         if caddy_config_check.changed
         else 'OK: Caddyfile up to date' 
      }}

- name: Stop caddy service
  systemd:
    name: caddy
    enabled: no
    state: stopped
  when: caddy_config_check.changed

- name: Update caddy config
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  when: caddy_config_check.changed

- name: Start caddy service
  systemd:
    name: caddy
    enabled: yes
    state: started
  when: caddy_config_check.changed
