---
- hosts: poone
  become: yes
  roles:
    - backup
  vars_files:
    - secrets.yaml
  vars:
    backup_paths:
      - /etc/transmission
      - /etc/prowlarr
      - /etc/vpn
      - /etc/radarr
      - /etc/sonarr
      - /etc/lidarr
      - /etc/jellyfin
      - /etc/navidrome
      - /var/log/backup
    backup_dir: /mnt/mount/backups
    backup_env_path: /mnt/mount/.env
    backup_retention_days: 30
    
    # # Unset backup_schedule to disable automatic backups
    # # Disable automatic backups
    # backup_schedule_enabled: false

    # # Enable automatic backups at 2:00 AM daily
    # backup_schedule: "0 0 2 * * *"
