---
- hosts: poone
  become: yes
  roles:
    - postgresdb
    # - common
    # - dockercomposeinit
  vars_files:
    - secrets.yaml
# ---
# - hosts: qmoran-laptop
#   become: yes
#   roles:
#     # - common
#   vars_files:
#     - secrets.yaml
