
[poone]
; po1 Raspberry pi
qmoran@100.68.254.44 ansible_ssh_private_key_file=~/.ssh/po/qmoran@po1_ed25519

; qmoran-laptop (personal laptop)
[qmoran-laptop]
qmoran@100.118.33.8 ansible_ssh_private_key_file=~/.ssh/po/qmoran@qmoran-laptop_ed25519