---
- name: Create postgres data directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - /var/lib/postgres
    - /var/lib/postgres/data

- name: Create docker container to run postgres
  docker_container:
    name: postgres
    image: postgres:18
    state: stopped
    restart_policy: unless-stopped
    volumes:
      - /var/lib/postgres/data:/var/lib/postgresql/data
    env:
      POSTGRES_PASSWORD: "{{ postgresql_root_password }}"
